/**
 * The resources this server can serve, and how it decides which of them to
 * advertise for a given project.
 *
 * A file-backed resource is listed only when its artifact is actually present,
 * so the listing never promises a read that would fail.
 */

import { readTextIfExists, vispPath } from "../../core/fs-utils.js";
import type { HyperActionEnvelopeV1 } from "../../kit/workflow-action-renderer.js";
import type { McpResourceDef } from "../mcp-server.js";

export type ResourceSpec = McpResourceDef & {
  path: string[];
  priority?: number;
};

export type CanonicalActionResourceV1 =
  | {
      resourceVersion: "1.0";
      availability: "available";
      envelope: HyperActionEnvelopeV1;
    }
  | {
      resourceVersion: "1.0";
      availability: "unavailable";
      authority: "none";
      reasonCode: "no_kit_signals";
      reason: string;
    }
  | {
      resourceVersion: "1.0";
      availability: "inconclusive";
      authority: "kit";
      reasonCode: string;
      reason: string;
    };

export const RESOURCE_SPECS: ResourceSpec[] = [
  {
    uri: "visp-hyper://current/session",
    name: "session.md",
    title: "Current Session",
    description: "Human-readable current session summary.",
    mimeType: "text/markdown",
    path: ["hyper", "current", "session.md"],
    priority: 0.8
  },
  {
    uri: "visp-hyper://current/context-pack",
    name: "context-pack.md",
    title: "Current Context Pack",
    description: "Task-scoped files, reasons, validation commands, and Kit warnings.",
    mimeType: "text/markdown",
    path: ["hyper", "current", "context-pack.md"],
    priority: 1
  },
  {
    uri: "visp-hyper://current/context-manifest",
    name: "context-manifest.json",
    title: "Current Context Manifest",
    description: "Machine-readable required reads, MCP resources, files, validation, and failure-pattern context.",
    mimeType: "application/json",
    path: ["hyper", "current", "context-manifest.json"],
    priority: 1
  },
  {
    uri: "visp-hyper://current/memory-pack",
    name: "memory-pack.md",
    title: "Current Memory Pack",
    description: "Recalled local or llm-memory entries for the active session.",
    mimeType: "text/markdown",
    path: ["hyper", "current", "memory-pack.md"],
    priority: 0.7
  },
  {
    uri: "visp-hyper://current/quality-gates",
    name: "quality-gates.md",
    title: "Current Quality Gates",
    description: "Validation, review, and scope gate guidance for the active session.",
    mimeType: "text/markdown",
    path: ["hyper", "current", "quality-gates.md"],
    priority: 0.9
  },
  {
    uri: "visp-hyper://current/agent-instructions",
    name: "agent-instructions.md",
    title: "Current Agent Instructions",
    description: "Tool-profile-specific instructions generated by Visp Hyper.",
    mimeType: "text/markdown",
    path: ["hyper", "current", "agent-instructions.md"]
  },
  {
    uri: "visp-hyper://current/handoff-json",
    name: "handoff.json",
    title: "Current Handoff JSON",
    description: "Structured handoff metadata for the active session.",
    mimeType: "application/json",
    path: ["hyper", "current", "handoff.json"],
    priority: 0.9
  },
  {
    uri: "visp-hyper://current/checkpoints",
    name: "checkpoints.md",
    title: "Current Checkpoints",
    description: "Checkpoint evidence and verify/review history for the active session.",
    mimeType: "text/markdown",
    path: ["hyper", "current", "checkpoints.md"],
    priority: 0.8
  },
  {
    uri: "visp-hyper://current/checkpoint-snapshot",
    name: "checkpoint-snapshot.json",
    title: "Current Checkpoint Snapshot",
    description: "Machine-readable hashed file snapshot captured at the latest checkpoint.",
    mimeType: "application/json",
    path: ["hyper", "current", "checkpoint-snapshot.json"],
    priority: 0.8
  },
  {
    uri: "visp-hyper://current/review-report",
    name: "review-report.md",
    title: "Current Review Report",
    description: "Latest deterministic local diff review generated by Visp Hyper.",
    mimeType: "text/markdown",
    path: ["hyper", "current", "review-report.md"]
  },
  {
    uri: "visp-hyper://prompts/handoff",
    name: "visp-hyper-handoff.prompt.md",
    title: "Rendered Handoff Prompt",
    description: "The rendered handoff prompt mirrored for tools that prefer prompt files.",
    mimeType: "text/markdown",
    path: ["prompts", "visp-hyper-handoff.prompt.md"]
  }
];

export const SURFACE_MANIFEST_RESOURCE: McpResourceDef = {
  uri: "visp-hyper://meta/surface-manifest",
  name: "surface-manifest.json",
  title: "MCP Surface Manifest",
  description: "Stable, hashed declaration of Visp Hyper MCP tools, resources, prompts, and safety posture.",
  mimeType: "application/json",
  annotations: {
    audience: ["user", "assistant"],
    priority: 1
  }
};

export const CONTEXT_FRESHNESS_RESOURCE: McpResourceDef = {
  uri: "visp-hyper://current/context-freshness",
  name: "context-freshness.json",
  title: "Current Context Freshness",
  description: "Machine-readable freshness status for the active context pack and grounded Kit artifacts.",
  mimeType: "application/json",
  annotations: {
    audience: ["user", "assistant"],
    priority: 1
  }
};

export const KIT_READ_CONTRACT_RESOURCE: McpResourceDef = {
  uri: "visp-hyper://current/kit-read-contract",
  name: "kit-read-contract.json",
  title: "Current Kit Read Contract",
  description: "Machine-readable Kit artifact read roles and freshness policy adopted into the active handoff.",
  mimeType: "application/json",
  annotations: {
    audience: ["user", "assistant"],
    priority: 1
  }
};

export const CANONICAL_ACTION_RESOURCE: McpResourceDef = {
  uri: "visp-hyper://current/canonical-action",
  name: "canonical-action.json",
  title: "Current Canonical Action",
  mimeType: "application/json",
  annotations: {
    audience: ["user", "assistant"],
    priority: 1
  }
};

/**
 * P21-HYPER-01. Computed, not a file mirror: reading it runs the collector, so
 * the only scout state any consumer can obtain is the receipted, validated
 * subset. The raw `.visp/hyper/current/scout-findings.json` is never served.
 */
export const SCOUT_FINDINGS_RESOURCE: McpResourceDef = {
  uri: "visp-hyper://current/scout-findings",
  name: "scout-findings.json",
  title: "Current Scout Findings",
  description: "Collected scout state: receipted entrypoints, path, affected tests, and unresolved questions.",
  mimeType: "application/json",
  annotations: {
    audience: ["user", "assistant"],
    priority: 0.9
  }
};

export async function resourceDefs(projectPath: string): Promise<McpResourceDef[]> {
  const defs: McpResourceDef[] = [
    SURFACE_MANIFEST_RESOURCE,
    CONTEXT_FRESHNESS_RESOURCE,
    KIT_READ_CONTRACT_RESOURCE,
    CANONICAL_ACTION_RESOURCE,
    SCOUT_FINDINGS_RESOURCE
  ];
  for (const spec of RESOURCE_SPECS) {
    const content = await readTextIfExists(vispPath(projectPath, ...spec.path));
    if (content === undefined) {
      continue;
    }
    defs.push(resourceDefFromSpec(spec));
  }
  return defs;
}

export function resourceDefFromSpec(spec: ResourceSpec): McpResourceDef {
  return {
    uri: spec.uri,
    name: spec.name,
    title: spec.title,
    description: spec.description,
    mimeType: spec.mimeType,
    ...(spec.priority === undefined
      ? {}
      : {
          annotations: {
            audience: ["user", "assistant"] as Array<"user" | "assistant">,
            priority: spec.priority
          }
        })
  };
}
