/**
 * Which memory mode a project gets when nobody has chosen one.
 *
 * The default was the constant `"file"`, and that one constant is why an
 * installed visp-memory with an initialised store sat inert for a whole
 * battleground round: `visp recall` refused with "the project is still
 * configured for file memory", and the single command that fixed it was never
 * run because nothing had said it was needed. Every other piece of the bridge
 * worked; only the default was wrong.
 *
 * SELECTING, NOT CREATING. Nothing here installs the CLI, initialises a store
 * or edits a configuration. It reports two facts that are already true of this
 * machine and this project, and the caller decides what to do with them.
 *
 * WHO ASKS. `initialConfig` consults this only when `config.json` is being
 * WRITTEN — a project that has never had one, and `visp init --force`, which
 * replaces the file wholesale. On the force path a recorded `file` can
 * therefore become `llm-memory`, which is what `--force` means; ordinary reads
 * never come here, so a recorded mode survives everything short of an explicit
 * regeneration. An earlier version of this note claimed a recorded mode "is
 * never overwritten from here", which was true of the first-write path and
 * wrong about the force path standing right beside it.
 */

import { join } from "node:path";

import { findExecutableOnPath } from "../core/executable-resolver.js";
import { fileExists } from "../core/fs-utils.js";
import { MEMORY_STORE_MANIFEST } from "./visp-memory-install.js";

/**
 * Whether `recall` and `learn` would reach a real store here: the visp-memory
 * CLI is on PATH **and** this project has been initialised against it.
 *
 * Both conditions, because either alone produces a worse failure than file
 * mode. The CLI without a store makes the verbs fail at the contract instead of
 * at the configuration; a store without the CLI has nothing to read it.
 */
export async function memoryStoreIsReachable(projectPath: string): Promise<boolean> {
  if ((await findExecutableOnPath("visp-memory")) === null) return false;
  return fileExists(join(projectPath, MEMORY_STORE_MANIFEST));
}

/**
 * The mode a project with no recorded configuration starts in.
 *
 * Called only where a `config.json` is being written for the first time (or
 * regenerated by `visp init --force`), so the PATH scan happens once per
 * project rather than on every config read.
 */
export async function defaultMemoryMode(projectPath: string): Promise<"file" | "llm-memory"> {
  return (await memoryStoreIsReachable(projectPath)) ? "llm-memory" : "file";
}
